name: Publish Astro.Remote
on:
  release: 
    types: [ published ]
jobs:
  Windows:
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix: 
        os: [ windows-latest ]
        dotnet: [ '3.1.x' ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup .NET Core - ${{ matrix.dotnet }}@${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ matrix.dotnet }}'
    - name: Build
      env: 
        GITHUB_USERNAME: qkmaxware
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd Astro.Remote
        cd Astro.Remote.Windows
        dotnet restore --configfile "..\..\nuget.config"
        msbuild Astro.Remote.Windows.csproj /restore /property:Configuration=Release
    - name: Compress
      uses: thedoctor0/zip-release@master
      with: 
        filename: 'windows.zip'
        directory: Astro.Remote.Windows\bin\Release\
    - name: Upload
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: "windows.zip"

  MacOS:
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix: 
        os: [ macos-latest ]
        dotnet: [ '3.1.x' ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup .NET Core - ${{ matrix.dotnet }}@${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ matrix.dotnet }}'
    - name: Build
      env: 
        GITHUB_USERNAME: qkmaxware
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd Astro.Remote
        cd Astro.Remote.macOS
        dotnet restore --configfile "..\..\nuget.config"
        msbuild Astro.Remote.macOS.csproj /restore /property:Configuration=Release
    - name: Compress
      uses: thedoctor0/zip-release@master
      with: 
        filename: 'macos.zip'
        directory: Astro.Remote.macOS\bin\Release\
    - name: Upload
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: "macos.zip"

  Android:
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix: 
        os: [ macos-latest ]
        dotnet: [ '3.1.x' ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup .NET Core - ${{ matrix.dotnet }}@${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ matrix.dotnet }}'
    - name: Build
      env: 
        GITHUB_USERNAME: qkmaxware
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd Astro.Remote
        cd Astro.Remote.Android
        dotnet restore --configfile "..\..\nuget.config"
        msbuild Astro.Remote.Android.csproj /restore /property:Configuration=Release
    - name: Compress
      uses: thedoctor0/zip-release@master
      with: 
        filename: 'android.zip'
        directory: Astro.Remote.Android\bin\Release\
    - name: Upload
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: "android.zip"

  IOS:
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix: 
        os: [ macos-latest ]
        dotnet: [ '3.1.x' ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup .NET Core - ${{ matrix.dotnet }}@${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ matrix.dotnet }}'
    - name: Build
      env: 
        GITHUB_USERNAME: qkmaxware
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd Astro.Remote
        cd Astro.Remote.iOS
        dotnet restore --configfile "..\..\nuget.config"
        msbuild Astro.Remote.iOS.csproj /restore /property:Configuration=Release
    - name: Compress
      uses: thedoctor0/zip-release@master
      with: 
        filename: 'ios.zip'
        directory: Astro.Remote.iOS\bin\Release\
    - name: Upload
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: "ios.zip"
    