name: Publish Website
on:
  release: 
    types: [ published ]
jobs:
  deploy:
    name: Deploy Github Pages
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup Chocolatey
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex

      - name: Setup DocFX
        shell: powershell
        run: choco install docfx -y

      - name: Build
        shell: powershell
        run: |
          docfx metadata docs/docfx.json
          docfx build docs/docfx.json -o . 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site